source $HOME\vimfiles\vundle.vimrc
source $HOME\vimfiles\custom_env.vimrc
source $HOME\vimfiles\ultisnips.vimrc
source $HOME\vimfiles\vimtex.vimrc
source $HOME\vimfiles\java.vimrc
source $HOME\vimfiles\go.vimrc
source $HOME\vimfiles\julia.vimrc
source $HOME\vimfiles\neocomplete.vimrc
source $HOME\vimfiles\vim-javacomplete2.vimrc
